const pet=document.querySelector('#pet'),sage=document.querySelector('#sage'),bubble=document.querySelector('#bubble'),status=document.querySelector('#status'),chat=document.querySelector('#chat'),messages=document.querySelector('#messages'),composer=document.querySelector('#composer'),prompt=document.querySelector('#prompt'),send=document.querySelector('#send'),closeChat=document.querySelector('#close-chat'),chatState=document.querySelector('#chat-state');let drag=null,bubbleTimer=null,reactionTimer=null,chatOpen=false;
const labels={dormant:'sleeping',awakening:'waking',idle:'idle',thinking:'thinking',speaking:'talking',working:'working',sleeping:'sleeping',concerned:'concerned',excited:'excited'};
function react(){pet.classList.remove('reacted');void pet.offsetWidth;pet.classList.add('reacted');clearTimeout(reactionTimer);reactionTimer=setTimeout(()=>pet.classList.remove('reacted'),520);}function say(text,ms=3200){bubble.textContent=text;bubble.classList.add('show');clearTimeout(bubbleTimer);bubbleTimer=setTimeout(()=>bubble.classList.remove('show'),ms);}function setStatus(label,active=false){status.textContent=label;pet.classList.toggle('active',active);chatState.textContent=label;}
async function wake(){try{return await window.sage.character.wake();}catch(error){console.error('[SAGE] wake failed',error);return false;}}
function addMessage(text,kind='sage'){const el=document.createElement('div');el.className=`message ${kind}`;el.textContent=String(text);messages.append(el);messages.scrollTop=messages.scrollHeight;return el;}
async function openChat(){if(chatOpen)return;chatOpen=true;await wake();await window.sage.window.resizeForChat(true);chat.hidden=false;pet.hidden=true;status.hidden=true;bubble.classList.remove('show');setStatus('idle');prompt.focus();}
async function closeChatSurface(){if(!chatOpen)return;chatOpen=false;chat.hidden=true;pet.hidden=false;status.hidden=false;await window.sage.window.resizeForChat(false);setStatus('idle');}
async function submitPrompt(text){const value=String(text||'').trim();if(!value||send.disabled)return;addMessage(value,'user');prompt.value='';send.disabled=true;setStatus('thinking',true);try{const result=await window.sage.assistant.ask(value);if(result?.kind==='confirmation'){const box=document.createElement('div');box.className='message sage confirm';const copy=document.createElement('div');copy.className='confirm-copy';copy.textContent=result.confirmation?.summary||'SAGE needs your confirmation.';const actions=document.createElement('div');actions.className='confirm-actions';const yes=document.createElement('button');yes.className='confirm-yes';yes.type='button';yes.textContent='Allow';const no=document.createElement('button');no.className='confirm-no';no.type='button';no.textContent='Cancel';yes.addEventListener('click',async()=>{yes.disabled=true;no.disabled=true;setStatus('thinking',true);try{const confirmed=await window.sage.assistant.confirm(result.confirmation.token);addMessage(confirmed?.text||'Done.','sage');setStatus('talking',true);}catch(error){addMessage(`I couldn’t complete that. ${error?.message||''}`,'sage');setStatus('concerned',true);}});no.addEventListener('click',()=>{yes.disabled=true;no.disabled=true;box.remove();setStatus('idle');});actions.append(yes,no);box.append(copy,actions);messages.append(box);messages.scrollTop=messages.scrollHeight;}else{addMessage(result?.text||'I’m here.','sage');setStatus(result?.state||'talking',true);}}catch(error){addMessage(`I couldn’t complete that. ${error?.message||'Please try again.'}`,'sage');setStatus('concerned',true);}finally{send.disabled=false;prompt.focus();}}
pet.addEventListener('dblclick',async()=>{react();say('Hey. 👋',1800);await openChat();});pet.addEventListener('keydown',async e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();react();await openChat();}});status.addEventListener('click',openChat);closeChat.addEventListener('click',closeChatSurface);composer.addEventListener('submit',e=>{e.preventDefault();submitPrompt(prompt.value);});
sage.draggable=false;sage.addEventListener('dragstart',e=>e.preventDefault());pet.addEventListener('dragstart',e=>e.preventDefault());
pet.addEventListener('pointerdown',async e=>{if(e.button!==0)return;await wake();drag={id:e.pointerId,x:e.screenX,y:e.screenY,moved:false};pet.setPointerCapture?.(e.pointerId);react();setStatus('awake',true);});pet.addEventListener('pointermove',e=>{if(!drag||drag.id!==e.pointerId)return;const dx=e.screenX-drag.x,dy=e.screenY-drag.y;if(Math.abs(dx)+Math.abs(dy)<2)return;drag.moved=true;window.sage.window.moveBy(dx,dy);drag.x=e.screenX;drag.y=e.screenY;});pet.addEventListener('pointerup',e=>{if(!drag||drag.id!==e.pointerId)return;const moved=drag.moved;drag=null;pet.releasePointerCapture?.(e.pointerId);if(moved){say('Here we are. ✨');setStatus('idle');}else{say('Hi. 👋',2200);setStatus('awake',true);}});pet.addEventListener('pointercancel',()=>{drag=null;setStatus('idle');});
window.sage.character.onStateChange(data=>{const next=String(data?.state||'idle');for(const name of Object.keys(labels))pet.classList.remove(`emotion-${name}`);pet.classList.add(`emotion-${next}`);setStatus(labels[next]||'idle',['awakening','thinking','speaking','working','concerned','excited'].includes(next));if(['speaking','working','concerned','excited'].includes(next))react();});window.sage.reminder.onDue(data=>{react();say(`Reminder: ${data.text}`,7000);setStatus('reminder',true);});window.sage.proactive.onSuggestion(data=>{react();say(data.text,7000);setStatus('notice',true);});window.addEventListener('load',()=>{pet.classList.add('emotion-sleeping');pet.classList.add('breathe');setStatus('sleeping',false);});