import test from'node:test';import assert from'node:assert/strict';import{CharacterRuntime}from'../app/core/runtime.mjs';

test('character runtime starts dormant and wakes through the intended lifecycle',()=>{const runtime=new CharacterRuntime('dormant');const changes=[];runtime.subscribe(change=>changes.push(change));assert.equal(runtime.state,'dormant');assert.equal(runtime.transition('idle'),false);assert.equal(runtime.transition('awakening'),true);assert.equal(runtime.state,'awakening');assert.equal(runtime.transition('idle'),true);assert.deepEqual(changes.map(x=>x.state),['awakening','idle']);runtime.dispose();});

test('character runtime rejects unsafe state jumps',()=>{const runtime=new CharacterRuntime('dormant');assert.equal(runtime.transition('thinking'),false);assert.equal(runtime.transition('sleeping'),false);assert.equal(runtime.state,'dormant');assert.equal(runtime.transition('awakening'),true);assert.equal(runtime.transition('sleeping'),true);assert.equal(runtime.transition('thinking'),false);assert.equal(runtime.state,'sleeping');runtime.dispose();});

test('character runtime helpers drive work and failure states safely',()=>{const runtime=new CharacterRuntime('dormant');assert.equal(runtime.wake(),true);assert.equal(runtime.state,'awakening');assert.equal(runtime.transition('idle'),true);assert.equal(runtime.beginThinking(),true);assert.equal(runtime.state,'thinking');assert.equal(runtime.beginWorking(),false);assert.equal(runtime.beginSpeaking(),true);assert.equal(runtime.state,'speaking');assert.equal(runtime.finish(),true);assert.equal(runtime.state,'idle');assert.equal(runtime.beginThinking(),true);assert.equal(runtime.fail(),true);assert.equal(runtime.state,'concerned');assert.equal(runtime.finish(),true);assert.equal(runtime.state,'idle');runtime.dispose();});

test('character runtime schedules and cancels idle sleep',()=>{let timer=null;let cleared=null;const runtime=new CharacterRuntime('idle',{sleepAfterMs:100,clock:(fn,ms)=>{timer={fn,ms};return timer;},clearClock:value=>{cleared=value;}});assert.equal(runtime.scheduleSleep(),true);assert.equal(timer.ms,100);runtime.cancelSleep();assert.equal(cleared,timer);assert.equal(runtime.state,'idle');assert.equal(runtime.scheduleSleep(),true);timer.fn();assert.equal(runtime.state,'sleeping');runtime.dispose();});

test('finishing active work schedules idle sleep automatically',()=>{let timer=null;const runtime=new CharacterRuntime('idle',{sleepAfterMs:100,clock:(fn,ms)=>{timer={fn,ms};return timer;},clearClock:()=>{}});assert.equal(runtime.beginThinking(),true);assert.equal(runtime.beginSpeaking(),true);assert.equal(runtime.finish(),true);assert.equal(runtime.state,'idle');assert.equal(timer?.ms,100);timer.fn();assert.equal(runtime.state,'sleeping');runtime.dispose();});

test('waking cancels a pending idle sleep timer',()=>{let timer=null;let cleared=null;const runtime=new CharacterRuntime('idle',{sleepAfterMs:100,clock:(fn,ms)=>{timer={fn,ms};return timer;},clearClock:value=>{cleared=value;}});assert.equal(runtime.scheduleSleep(),true);assert.equal(runtime.wake(),true);assert.equal(runtime.state,'idle');assert.equal(cleared,timer);timer.fn();assert.equal(runtime.state,'idle');runtime.dispose();});
