import{app,BrowserWindow,globalShortcut,ipcMain,screen,shell,Notification}from'electron';
import{randomUUID}from'node:crypto';import path from'node:path';import{fileURLToPath}from'node:url';import{CharacterRuntime}from'./core/runtime.mjs';import{MemoryStore}from'./core/memory.mjs';import{ToolPolicy}from'./core/policy.mjs';import{AssistantCore}from'./core/assistant.mjs';import{ModelAdapter}from'./core/model.mjs';import{ToolRegistry}from'./core/tools.mjs';import{ReminderStore}from'./core/reminders.mjs';import{ExperienceStore}from'./core/experience.mjs';import{ProactiveEngine}from'./core/proactive.mjs';
const __dirname=path.dirname(fileURLToPath(import.meta.url));let win;let networkAllowed=false;const defaultBounds={width:300,height:430};const runtime=new CharacterRuntime('idle');const pendingActions=new Map();const CONFIRMATION_TTL=120000;let memory,assistant,policy,model,tools,reminders,experience,proactive;
function workArea(){return screen.getPrimaryDisplay().workArea;}function clamp(x,y,w,h){const b=workArea();return{x:Math.max(b.x,Math.min(Math.round(x),b.x+b.width-w)),y:Math.max(b.y,Math.min(Math.round(y),b.y+b.height-h))};}function placeCorner(){if(!win)return;const b=workArea(),[w,h]=win.getSize(),p=clamp(b.x+b.width-w-30,b.y+b.height-h-20,w,h);win.setPosition(p.x,p.y);}
function createWindow(){win=new BrowserWindow({...defaultBounds,minWidth:280,minHeight:400,maxWidth:470,maxHeight:650,frame:false,transparent:true,resizable:false,movable:true,alwaysOnTop:true,skipTaskbar:true,hasShadow:false,backgroundColor:'#00000000',show:false,webPreferences:{preload:path.join(__dirname,'preload.mjs'),contextIsolation:true,nodeIntegration:false,sandbox:true}});win.setAlwaysOnTop(true,'floating');win.setMenuBarVisibility(false);win.loadFile(path.join(__dirname,'renderer','index.html'));win.once('ready-to-show',()=>{placeCorner();win.show();});}
function issueConfirmation(result){const token=randomUUID();pendingActions.set(token,{action:result.confirmation,expiresAt:Date.now()+CONFIRMATION_TTL});return{...result,confirmation:{summary:result.confirmation.summary,token}};}
function consumeConfirmation(token){const item=pendingActions.get(String(token));pendingActions.delete(String(token));if(!item||item.expiresAt<Date.now())throw Object.assign(new Error('That permission request has expired. Please ask me again.'),{code:'CONFIRMATION_EXPIRED'});return item.action;}
async function boot(){await app.whenReady();memory=new MemoryStore(path.join(app.getPath('userData'),'memory.json'));await memory.load();reminders=new ReminderStore(path.join(app.getPath('userData'),'reminders.json'));await reminders.load();experience=new ExperienceStore(path.join(app.getPath('userData'),'experience.json'));await experience.load();networkAllowed=experience.networkAllowed;policy=new ToolPolicy({networkAllowed});tools=new ToolRegistry({policy,handlers:{'memory.remember':async({text})=>memory.remember(text,{source:'conversation',userApproved:true}),'memory.clear':()=>memory.clear(),'reminder.create':args=>reminders.add(args.text,args.when),'open.url':async({url})=>{if(!/^https?:\/\//i.test(url))throw new Error('Only http and https URLs are allowed.');await shell.openExternal(url);return{url};}}});model=new ModelAdapter({policy});assistant=new AssistantCore({memory,policy,model,tools});reminders.start(item=>{if(Notification.isSupported())new Notification({title:'SAGE reminder',body:item.text}).show();win?.webContents.send('reminder:due',{text:item.text});});proactive=new ProactiveEngine({experience,reminders,onSuggestion:async suggestion=>{if(Notification.isSupported())new Notification({title:'SAGE',body:suggestion.text}).show();win?.webContents.send('proactive:suggestion',suggestion);}});if(experience.proactiveEnabled)proactive.start();createWindow();globalShortcut.register('CommandOrControl+Shift+S',()=>win?.isVisible()?win.hide():win.show());}
ipcMain.handle('window:toggle-visibility',()=>{if(!win)return false;if(win.isVisible())win.hide();else win.show();return win.isVisible();});
ipcMain.handle('window:set-interactive',(_e,v)=>{const enabled=Boolean(v);win?.setIgnoreMouseEvents(!enabled,{forward:true});return enabled;});ipcMain.handle('window:move-by',(_e,dx,dy)=>{if(!win||!Number.isFinite(dx)||!Number.isFinite(dy))return false;const[x,y]=win.getPosition(),[w,h]=win.getSize(),p=clamp(x+dx,y+dy,w,h);win.setPosition(p.x,p.y);return true;});
ipcMain.handle('window:resize-chat',(_e,open)=>{if(!win)return false;const next=open?{width:455,height:610}:defaultBounds;const[x,y]=win.getPosition(),[w,h]=win.getSize(),p=clamp(x-(next.width-w),y-(next.height-h),next.width,next.height);win.setBounds({x:p.x,y:p.y,width:next.width,height:next.height},true);return true;});
ipcMain.handle('window:close',()=>app.quit());ipcMain.handle('window:toggle-always-on-top',()=>{const value=!win.isAlwaysOnTop();win.setAlwaysOnTop(value,'floating');return value;});
ipcMain.handle('assistant:ask',async(_e,text)=>{runtime.transition('thinking');try{const result=await assistant.respond(text);return result?.kind==='confirmation'?issueConfirmation(result):result;}finally{runtime.transition('idle');}});
ipcMain.handle('assistant:confirm',async(_e,token)=>{runtime.transition('thinking');try{return await assistant.confirm(consumeConfirmation(token));}finally{runtime.transition('idle');}});
ipcMain.handle('memory:list',()=>memory.snapshot());ipcMain.handle('memory:search',(_e,q)=>memory.search(q));ipcMain.handle('memory:clear',()=>memory.clear());ipcMain.handle('network:get',()=>networkAllowed);ipcMain.handle('network:set',async(_e,v)=>{networkAllowed=Boolean(v);policy.networkAllowed=networkAllowed;await experience.setNetworkAllowed(networkAllowed);return networkAllowed;});ipcMain.handle('voice:can-use',()=>({allowed:networkAllowed,reason:networkAllowed?'Voice input may use a speech recognition service.':'Enable Online access before using voice input.'}));ipcMain.handle('voice:get-preference',()=>experience.voiceInputEnabled);ipcMain.handle('voice:set-preference',async(_e,v)=>experience.setVoiceInputEnabled(v));ipcMain.handle('reminder:list',()=>reminders.snapshot());ipcMain.handle('experience:get',()=>experience.snapshot());ipcMain.handle('proactive:get',()=>experience.proactiveEnabled);ipcMain.handle('proactive:set',async(_e,v)=>{const enabled=await experience.setProactiveEnabled(v);if(enabled)proactive.start();else proactive.stop();return enabled;});
app.on('will-quit',()=>{globalShortcut.unregisterAll();pendingActions.clear();reminders?.stop();proactive?.stop();});app.on('window-all-closed',e=>e.preventDefault());boot().catch(e=>{console.error('[SAGE] startup failure',e);app.quit();});
