import{contextBridge,ipcRenderer}from'electron';
contextBridge.exposeInMainWorld('sage',Object.freeze({
 window:Object.freeze({toggleVisibility:()=>ipcRenderer.invoke('window:toggle-visibility'),setInteractive:v=>ipcRenderer.invoke('window:set-interactive',Boolean(v)),moveBy:(x,y)=>ipcRenderer.invoke('window:move-by',Number(x),Number(y)),resizeForChat:v=>ipcRenderer.invoke('window:resize-chat',Boolean(v)),close:()=>ipcRenderer.invoke('window:close'),alwaysOnTop:()=>ipcRenderer.invoke('window:toggle-always-on-top')}),
 assistant:Object.freeze({ask:t=>ipcRenderer.invoke('assistant:ask',String(t)),confirm:token=>ipcRenderer.invoke('assistant:confirm',String(token))}),
 memory:Object.freeze({list:()=>ipcRenderer.invoke('memory:list'),search:q=>ipcRenderer.invoke('memory:search',String(q)),remove:id=>ipcRenderer.invoke('memory:remove',String(id)),clear:()=>ipcRenderer.invoke('memory:clear'),export:()=>ipcRenderer.invoke('memory:export')}),
 reminder:Object.freeze({list:()=>ipcRenderer.invoke('reminder:list'),onDue:fn=>ipcRenderer.on('reminder:due',(_e,data)=>fn(data))}),
 network:Object.freeze({get:()=>ipcRenderer.invoke('network:get'),set:v=>ipcRenderer.invoke('network:set',Boolean(v))}),
 voice:Object.freeze({canUse:()=>ipcRenderer.invoke('voice:can-use'),getPreference:()=>ipcRenderer.invoke('voice:get-preference'),setPreference:v=>ipcRenderer.invoke('voice:set-preference',Boolean(v))}),
 experience:Object.freeze({get:()=>ipcRenderer.invoke('experience:get')}),
 proactive:Object.freeze({get:()=>ipcRenderer.invoke('proactive:get'),set:v=>ipcRenderer.invoke('proactive:set',Boolean(v)),onSuggestion:fn=>ipcRenderer.on('proactive:suggestion',(_e,data)=>fn(data))}),
 plugins:Object.freeze({list:()=>ipcRenderer.invoke('plugin:list')}),
 context:Object.freeze({get:()=>ipcRenderer.invoke('context:get')})
}));
