import{identityPrompt}from'./identity.mjs';
const DEFAULT_MODEL=process.env.SAGE_OLLAMA_MODEL||'llama3.2:3b';
const LOCAL_TIMEOUT=Number(process.env.SAGE_LOCAL_MODEL_TIMEOUT_MS||30000);const ONLINE_TIMEOUT=Number(process.env.SAGE_ONLINE_MODEL_TIMEOUT_MS||20000);
export class ModelAdapter{
 constructor({policy}){this.policy=policy;this.provider=process.env.SAGE_MODEL_PROVIDER||'ollama';this.ollamaUrl=process.env.SAGE_OLLAMA_URL||'http://127.0.0.1:11434/api/chat';this.model=DEFAULT_MODEL;}
 async chat(messages){if(this.provider==='openai')return this.#openAI(messages);if(this.provider==='ollama')return this.#ollama(messages);throw new Error(`Unknown model provider: ${this.provider}`);}
 async #request(url,options,timeout){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{return await fetch(url,{...options,signal:controller.signal});}catch(error){if(error?.name==='AbortError')throw new Error('The reasoning engine timed out.');throw error;}finally{clearTimeout(timer);}}
 async #ollama(messages){const response=await this.#request(this.ollamaUrl,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({model:this.model,messages:[{role:'system',content:identityPrompt()},...messages],stream:false,options:{temperature:.7}})},LOCAL_TIMEOUT);if(!response.ok)throw new Error(`Local model unavailable (${response.status})`);const data=await response.json();return String(data?.message?.content||'').trim();}
 async #openAI(messages){if(!this.policy.networkAllowed)throw new Error('Online access is disabled.');const key=process.env.OPENAI_API_KEY;if(!key)throw new Error('OPENAI_API_KEY is not configured.');const response=await this.#request(process.env.SAGE_OPENAI_URL||'https://api.openai.com/v1/chat/completions',{method:'POST',headers:{authorization:`Bearer ${key}`,'content-type':'application/json'},body:JSON.stringify({model:process.env.SAGE_OPENAI_MODEL||'gpt-5-mini',messages:[{role:'system',content:identityPrompt()},...messages],temperature:.7})},ONLINE_TIMEOUT);if(!response.ok)throw new Error(`Online model unavailable (${response.status})`);const data=await response.json();return String(data?.choices?.[0]?.message?.content||'').trim();}
}
